# Generated by Django 3.1 on 2020-08-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_only', '0005_auto_20200817_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(upload_to='one/'),
        ),
    ]
