# Generated by Django 3.1 on 2020-08-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_only', '0006_auto_20200817_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ModelFile',
            field=models.FileField(default='try_models.glb', upload_to='two/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='try1.png', upload_to='one/'),
        ),
    ]
